services:
  #server
  server:
    image: server:latest
    build:
      context: ./server
    environment:
      #application port
      - SERVER_PORT_APP=8081
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"

  #service
  service:
    image: service:latest
    build:
      context: ./service
    environment:
      #application port
      - SERVICE_PORT_APP=8083
      #eureka server port
      - SERVER_PORT_APP=8081
      - SPRING_PROFILES_ACTIVE=docker
      - SERVICE_DB_SCHEMA=eureka_service
      - DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=admin
    ports:
      - "8083:8083"
    links:
      - server

  #client
  client:
    image: client
    build:
      context: ./client
    environment:
      #application port
      - CLIENT_PORT_APP=8082
      #eureka server port
      - SERVER_PORT_APP=8081
      - SPRING_PROFILES_ACTIVE=docker
      - ClIENT_DB_SCHEMA=eureka_client
      - DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=admin
    ports:
      - "8082:8082"
    links:
      - server