spring:
  application:
    name: eureka-service
  jpa:
    properties:
      hibernate:
        default_schema: ${SERVICE_DB_SCHEMA}
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog.yml
    #it is needed to be setup explicitly or will apply to public schema
    default-schema: ${SERVICE_DB_SCHEMA}

server:
  port: ${SERVICE_PORT_APP}
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:${SERVER_PORT_APP}/eureka/
feign:
  client:
    config:
      default:
        loggerLevel: FULL