spring:
  application:
    name: eureka-client
server:
  port: ${CLIENT_PORT_APP}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:${SERVER_PORT_APP}/eureka/